/* CM32M4xxR */
MEMORY
{
	FLASH : ORIGIN = 0x08000000, LENGTH = 512k
	RAM : ORIGIN = 0x20000000, LENGTH = 128k
}

/*代码段进FLASH，就地执行*/
REGION_ALIAS("REGION_TEXT", FLASH);
/*只读数据段进FLASH*/
REGION_ALIAS("REGION_RODATA", FLASH);
/*变量段进RAM*/
REGION_ALIAS("REGION_DATA", RAM);
/*未初始化变量段进RAM*/
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
