[env]

[build]
# target = "thumbv7m-none-eabi"
target = "thumbv7em-none-eabihf"
# target = "riscv32imac-unknown-none-elf"
# target = "thumbv6m-none-eabi"

[target.riscv32imac-unknown-none-elf]
runner = 'D:\\NucleiStudio\\toolchain\\gcc\\bin\\riscv-nuclei-elf-gdb.exe -x openocd.gdb'
rustflags = [
  "-Clink-arg=-Tmemory.x",
  "-Clink-arg=-Tlink.x",
]

[target.thumbv7em-none-eabihf]
# runner = 'probe-run --chip  STM32F427VITx'
# runner = 'probe-run --chip  STM32H7B0VBTx'
runner = 'probe-run --chip  STM32F411CEUx'
#runner = "/Volumes/gqf/toolchain/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gdb -q -x openocd.gdb"
# runner = "D:\\toolchain\\arm\\bin\\arm-none-eabi-gdb -q -x openocd.gdb"
rustflags = [
  # "-Clink-arg=-Tmemory.x",
  "-Clink-arg=-Tlink.x",
]

[target.thumbv7m-none-eabi]
runner = "/Volumes/gqf/toolchain/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gdb -q -x openocd.gdb"
# runner = "D:\\toolchain\\arm\\bin\\arm-none-eabi-gdb -q -x openocd.gdb"
rustflags = [
  # "-Clink-arg=-Tmemory.x",
  "-Clink-arg=-Tlink.x",
]

[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs -d"
# runner = "probe-run --chip RP2040"
rustflags = [
  "-Clink-arg=--nmagic",
  "-Clink-arg=-Tlink.x",
  "-Cinline-threshold=5",
  "-Cno-vectorize-loops",
]
