[env]

[build]
target = "thumbv7em-none-eabihf"
# target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
runner = 'riscv64-unknown-elf-gdb -x openocd.gdb'
rustflags = [
  "-Clink-arg=-Tmemory.x",
  "-Clink-arg=-Tlink.x",
]

[target.thumbv7em-none-eabihf]
# runner = 'probe-run --chip stm32f401'
# runner = "/Volumes/gqf/toolchain/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gdb -q -x openocd.gdb"
runner = "D:\\toolchain\\arm\\bin\\arm-none-eabi-gdb -q -x openocd.gdb"
rustflags = [
  # "-Clink-arg=-Tmemory.x",
  "-Clink-arg=-Tlink.x",
]
