[env]

[build]
target = "thumbv7em-none-eabihf"

[target.riscv32imac-unknown-none-elf]
runner = 'riscv64-unknown-elf-gdb -x openocd.gdb'
rustflags = [
  "-Clink-arg=-Tmemory.x",
  "-Clink-arg=-Tlink.x",
]

[target.thumbv7em-none-eabihf]
runner = 'probe-run --chip stm32f401'
rustflags = [
  "-C",
  "link-arg=-Tlink.x",
]
